#issue3 database star created
jaspreet338/tech-pandas-STAR pull request #11
Opened 2023-02-15 14:55 UTC by Mesgna616

## Naming Rules

Name your PR like this: ISSUENUMBER-TITLE-YOURNAME

## Description

Write a summary of your change. Explain why you have made it.

## Related to

Make sure you include the issue number with a hash sign # so Github can link this PR to the right issue, like this:

Fixes #1

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have carefully reviewed my own code
- [ ] I have commented my code
- [ ] I have updated any documentation

2023-02-16 12:15 UTC, TsioneTemesgenAbraham requested changes
Mark suggests we add a foreign key to link it to the users table

2023-02-16 22:12 UTC, Mesgna616 commented
> Mark suggests we add a foreign key to link it to the users table

I  have modified it but its creating issues with the post method. You might need to look and work around the post method i did. Thank you

2023-02-19 01:19 UTC, TsioneTemesgenAbraham approved these changes

2023-02-19 12:47 UTC, MarkFarmiloe approved these changes

2023-02-19 19:30 UTC, merged