Singel star view page/ mesgna/fatema
jaspreet338/tech-pandas-STAR pull request #110
Opened 2023-03-09 11:38 UTC by Mesgna616

## Naming Rules

Name your PR like this: ISSUENUMBER-TITLE-YOURNAME

## Description

Write a summary of your change. Explain why you have made it.

## Related to

Make sure you include the issue number with a hash sign # so Github can link this PR to the right issue, like this:

Fixes #1

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have carefully reviewed my own code
- [ ] I have commented my code
- [ ] I have updated any documentation

2023-03-09 15:06 UTC, MarkFarmiloe submitted a review, later dismissed

2023-03-09 15:22 UTC, MarkFarmiloe requested changes
Need to merge main into this branch and resolve the conflict in the SingleStar.js file.
You need to keep the 'current' changes and then manually add in the 
 {user.role === "TA" || user.role === "mentor" ? null : (
near the end.

2023-03-10 10:35 UTC, MarkFarmiloe approved these changes

2023-03-10 10:36 UTC, merged

2023-03-13 18:53 UTC, FatemRahimi commented
> Need to merge main into this branch and resolve the conflict in the SingleStar.js file. You need to keep the 'current' changes and then manually add in the {user.role === "TA" || user.role === "mentor" ? null : ( near the end.



> Need to merge main into this branch and resolve the conflict in the SingleStar.js file. You need to keep the 'current' changes and then manually add in the {user.role === "TA" || user.role === "mentor" ? null : ( near the end.
Hey Mark I got some conflicts I can not resolve it.