2-GitHub login-Tsione
jaspreet338/tech-pandas-STAR pull request #13
Opened 2023-02-16 12:22 UTC by TsioneTemesgenAbraham

## Naming Rules

Name your PR like this: ISSUENUMBER-TITLE-YOURNAME

## Description

Complete OAuth Login as far as possible at this stage.

## Related to

Make sure you include the issue number with a hash sign # so Github can link this PR to the right issue, like this:

Implements(partially) #2

## Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have carefully reviewed my own code
- [ ] I have commented my code
- [ ] I have updated any documentation

2023-02-16 12:24 UTC, TsioneTemesgenAbraham commented
Suggest extra issues raised to do 
-  Create users table
-  Create session table
Also waiting on merge of issue #6

2023-02-21 16:09 UTC, jaspreet338 requested changes

2023-02-21 16:09 UTC, jaspreet338 commented on server/api.js
> +	const gh_user = await user_resp.json();
i think it called github_user instead of gh_user

2023-02-24 16:39 UTC, jaspreet338 approved these changes

2023-02-24 16:39 UTC, merged