Issue#5 -Mesgna -Woldeab
jaspreet338/tech-pandas-STAR pull request #15
Opened 2023-02-16 21:46 UTC by Mesgna616

## Naming Rules

Name your PR like this: ISSUENUMBER-TITLE-YOURNAME

## Description

Write a summary of your change. Explain why you have made it.

## Issue#5 CRUD and Star API Created 

Make sure you include the issue number with a hash sign # so Github can link this PR to the right issue, like this:

Fixes #1

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have carefully reviewed my own code
- [ ] I have commented my code
- [ ] I have updated any documentation

2023-02-17 09:54 UTC, MarkFarmiloe requested changes

2023-02-17 09:54 UTC, MarkFarmiloe commented on server/starAPI.js
> +		res.status(200).json(error);
You shouldn't be returning status 200 when there has been an error.
In this case, it should only happen if the database is down or something like that, so 500 is probably the one to use.

2023-02-17 09:54 UTC, MarkFarmiloe commented on server/starDatabase.sql
> +  user_id SERIAL,
SERIAL is used to ask PG to generate the value each time, which will be an INT value.
That's fine for the Primary Key, but not for Foreign Keys as we need to supply the value.
SO you need to change this to user_id INT

2023-02-18 22:20 UTC, TsioneTemesgenAbraham approved these changes
Hey Mesgna. Great job!
You did the right thing by creating another file for the STAR API. It helped me understand the code better.

2023-02-19 12:46 UTC, MarkFarmiloe commented on server/starAPI.js
> +		res.status(200).json(error);
Not a big enough issue to hold up the merge.

2023-02-19 12:46 UTC, MarkFarmiloe approved these changes

2023-02-19 19:30 UTC, merged